apiVersion: v1
kind: Pod
metadata:
  name: {{ podName }}
spec: 
  volumes:
  - name: bdb-pv
    persistentVolumeClaim:
      claimName: azurefile
  - name: env-config
    secret:
      secretName: dev-env
      optional: false
  containers:
  - name: bdb2
    image: bdbcr.azurecr.io/bdb:{{image_version|default("2.1.6")}}
    command: ["/bin/bash", "-c"]
    args:
    - mkdir ~/repo &&
      git clone -b {{ branch }} --single-branch --shallow-submodules https://github.com/rosejb95/etldemo.git ~/repo &&
      chown -R 1000:100 ~/repo &&
      /usr/sbin/sshd -D
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 22
      name: ssh-port
    volumeMounts:
    - name: bdb-pv
      mountPath: "/mnt/etlshare"
    - name: env-config
      mountPath: '/mnt/secret'
      readOnly: true
  imagePullSecrets:
  - name: bdbcr-creds