apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      volumes:
      - name: bdb-pv
        persistentVolumeClaim:
          claimName: azurefile
      - name: env-config
        secret:
          secretName: dev-env
          optional: false
      containers:
      - name: bdb2
        image: {{ image_tag }}
        command: ["/bin/bash", "-c"]
        args:
        - mkdir ~/repo &&
          git clone -b {{ branch }} --single-branch --shallow-submodules https://github.com/rosejb95/etldemo.git ~/repo &&
          chown -R 1000:100 ~/repo &&
          {{ command }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: ssh-port
        volumeMounts:
        - name: bdb-pv
          mountPath: "/mnt/etlshare"
        - name: env-config
          mountPath: '/mnt/secret'
          readOnly: true
      imagePullSecrets:
      - name: bdbcr-creds
      restartPolicy: Never
  backoffLimit: 0
