apiVersion: v1
kind: Pod
metadata:
  name: {{ required "Must specify value podName for name of the k8s pod." .Values.podName }}
spec: 
  volumes:
  - name: bdb-pv
    persistentVolumeClaim:
      claimName: azurefile
  - name: env-config
    secret:
      secretName: dev-env
      optional: false
  containers:
  - name: bdb2
    image: bdbcr.azurecr.io/bdb:2.1.4
    command: ["/bin/bash", "-c"]
    args:
    - mkdir ~/repo &&
      git clone -b {{ required "Must specify value branch for code branch." .Values.branch }} --single-branch --shallow-submodules git@github.com:rosejb95/etldemo.git ~/repo;
      chown -R 1000:100 ~/repo;
      /usr/sbin/sshd -D
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 22
      name: ssh-port
    volumeMounts:
    - name: bdb-pv
      mountPath: "/mnt/etlshare"
    - name: env-config
      mountPath: '/mnt/secret'
      readOnly: true
  imagePullSecrets:
  - name: bdbcr-creds